### ISSUE TITLE
many models pattern vs regular regression based models - responsible compute - accuracy improvements - available research?

### ISSUE THREAD

**Issue by rquintino** [microsoft/solution-accelerator-many-models#106]
Hi there! we've been exploring this pattern occasionally (frequently using facebook prophet), but these days, especially if at large scale (# of time series),  I was wondering if there is actually any known research on accuracy improvements using this vs a more typical single fit regression approach, (using xgboost, lgbm), which should account easily for the additional granularity attributes.

Asking mainly because of compute considerations this pattern requires, especially as shown in the samples on this repo. Raising some responsible AI considerations honestly, is this really worth the effort and compute? Anyone studied this? Would love to know and deep dive.

Also taking into account that as far as I can remember Azure AutoML already has a forecast option for additional granularity attributes like stores, locations,etc. So not clear what's the benefit of parallel automl by store? Is it not redundant? (current version parameter is time_series_id_column_names)

Some related threads & refs:
multiple time series (ex: locations, skus,stores) | prophet (many models) vs regression (single model) | scalability 
https://github.com/facebook/prophet/issues/1687

Fine-Grained Time Series Forecasting At Scale With Facebook Prophet And Apache Spark
https://databricks.com/blog/2020/01/27/time-series-forecasting-prophet-spark.html

**Comment by Aniththa** [comment]
Looks like this has been answered on the other thread. Will close this for now. Please do feel free to reach out if you have any additional questions.
