### ISSUE TITLE
ImportError: cannot import name 'list_remove_none_object'

### ISSUE THREAD

**Issue by jingwora** [microsoft/solution-accelerator-many-models#111]
I have runned example as below. 
00_Setup_AML_Workspace.ipynb
01_Data_Preparation.ipynb
02_AutoML_Training_Pipeline.ipynb

There is an error in 02_AutoML_Training_Pipeline.ipynb.
**ImportError: cannot import name 'list_remove_none_object'**

Could you tell me how to fix it?

-----------------------------------------

Environment:
Azure compute instant

SDK version | 1.18.0

!pip install --upgrade azureml-sdk[automl]
!pip install --upgrade azureml-pipeline-steps
!pip install azureml.pipeline.steps

------------------------------------------

in 02_AutoML_Training_Pipeline.ipynb
There are some warning as below.

-----------------------------

from scripts.helper import get_automl_environment
train_env = get_automl_environment(workspace=ws, automl_settings_dict=automl_settings)

-----------------------------

WARNING:root:Received unrecognized parameter task
WARNING:root:Received unrecognized parameter experiment_timeout_hours
WARNING:root:Received unrecognized parameter time_column_name
WARNING:root:Received unrecognized parameter max_horizon
WARNING:root:Received unrecognized parameter group_column_names
WARNING:root:Received unrecognized parameter grain_column_names

There is an error in below code:

-----------------------------

from scripts.helper import build_parallel_run_config

# PLEASE MODIFY the following three settings based on your compute and experiment timeout.
node_count=2
process_count_per_node=8
run_invocation_timeout=3700 # this timeout(in seconds) is inline with AutoML experiment timeout or (no of iterations * iteration timeout)

parallel_run_config = build_parallel_run_config(train_env, compute, node_count, process_count_per_node, run_invocation_timeout)

-----------------------------

train_envtrain_env---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-8-fbc046aada7f> in <module>
      6 run_invocation_timeout=3700 # this timeout(in seconds) is inline with AutoML experiment timeout or (no of iterations * iteration timeout)
      7 
----> 8 parallel_run_config = build_parallel_run_config(, compute, node_count, process_count_per_node, run_invocation_timeout)

/mnt/batch/tasks/shared/LS_root/mounts/clusters/std-ds3-v2-m-aml/code/manymodels_05/Automated_ML/02_AutoML_Training_Pipeline/scripts/helper.py in build_parallel_run_config(train_env, compute, nodecount, workercount, timeout)
     31 
     32 def build_parallel_run_config(, compute, nodecount, workercount, timeout):
---> 33     from azureml.pipeline.steps import ParallelRunConfig
     34     from common.scripts.helper import validate_parallel_run_config
     35     parallel_run_config = ParallelRunConfig(

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/pipeline/steps/__init__.py in <module>
     32 from .estimator_step import EstimatorStep
     33 from .mpi_step import MpiStep
---> 34 from .hyper_drive_step import HyperDriveStep, HyperDriveStepRun
     35 from .azurebatch_step import AzureBatchStep
     36 from .module_step import ModuleStep

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/pipeline/steps/hyper_drive_step.py in <module>
     10 from azureml.pipeline.core._module_builder import _ModuleBuilder
     11 from azureml.pipeline.core.graph import ParamDef, OutputPortBinding
---> 12 from azureml.train.hyperdrive.run import HyperDriveRun
     13 
     14 

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/train/hyperdrive/__init__.py in <module>
     15 from .policy import BanditPolicy, MedianStoppingPolicy, NoTerminationPolicy, TruncationSelectionPolicy, \
     16     EarlyTerminationPolicy
---> 17 from .runconfig import HyperDriveRunConfig, HyperDriveConfig, PrimaryMetricGoal
     18 from .run import HyperDriveRun
     19 from .sampling import RandomParameterSampling, GridParameterSampling, BayesianParameterSampling, HyperParameterSampling

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/train/hyperdrive/runconfig.py in <module>
     17 from azureml.train.hyperdrive.policy import NoTerminationPolicy, _policy_from_dict
     18 from azureml.train.hyperdrive.sampling import BayesianParameterSampling, _sampling_from_dict
---> 19 from azureml.train._estimator_helper import _get_arguments
     20 from azureml._restclient.constants import RunStatus
     21 from azureml.data.constants import _HYPERDRIVE_SUBMIT_ACTIVITY

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/train/_estimator_helper.py in <module>
     15 from azureml.data.output_dataset_config import OutputDatasetConfig
     16 from azureml.exceptions import ComputeTargetException, UserErrorException, TrainingException
---> 17 from azureml._base_sdk_common.utils import convert_dict_to_list, merge_list, \
     18     list_remove_none_object, list_remove_empty_strings
     19 from azureml.data.data_reference import DataReference

**ImportError: cannot import name 'list_remove_none_object'**

**Comment by sagarsumant** [comment]
Hello @jingwora - Sorry that you are facing this trouble. I tried reproing your problem like this 

-  creating vanilla conda environment and installing azureml-sdk[automl]==1.18.0
-  install jupyter notebook(conda install nb_conda).
- Clone github notebooks and run them in the sequence you specified

Unfortunately I am not able to repro what you are seeing. So my guess at this point is when you updated your current environment it may have partial updates to 1.18.0 and hence there might be dependency mismatch leading to failures that you are seeing.

There are two options
1. Do a pip freeze and ensure the dependency tree for azureml-* packages has the right versions 1.18.*
2. Follow steps [here](https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/automated-machine-learning) to create new conda environment with the right dependencies.

**Comment by jingwora** [comment]
Thank you for fast reponse.

I decide to create new azure compute instant which should have the latest azureml-sdk version.
All azureml versions is 1.18 as in pip freeze below. 

I have cloned github notebooks and run them in the sequence you specified
00_Setup_AML_Workspace.ipynb
01_Data_Preparation.ipynb
02_AutoML_Training_Pipeline.ipynb

In 02_AutoML_Training_Pipeline.ipynb, there is still warning show up.

-------------

from scripts.helper import get_automl_environment
train_env = get_automl_environment(workspace=ws, automl_settings_dict=automl_settings)

-------------

WARNING - Received unrecognized parameter task
WARNING - Received unrecognized parameter experiment_timeout_hours
WARNING - Received unrecognized parameter time_column_name
WARNING - Received unrecognized parameter max_horizon
WARNING - Received unrecognized parameter group_column_names
WARNING - Received unrecognized parameter grain_column_names

running is success but there is only one model created.
VotingEnsemble

Where should I look to fix this issue?

PS: Please let me know if you need more info from the run.

-------------

pip freeze:
+++++++++
absl-py==0.11.0
adal==1.2.5
aiohttp==3.7.2
aiohttp-cors==0.7.0
aioredis==1.3.1
alembic==1.4.1
ansiwrap==0.8.4
antlr4-python3-runtime==4.7.2
applicationinsights==0.11.9
argcomplete==1.12.1
argon2-cffi @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi_1602546564419/work
astor==0.8.1
astroid==2.4.2
async-generator==1.10
async-timeout==3.0.1
atari-py==0.2.6
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1605083924122/work
autopep8==1.5.4
azure-appconfiguration==1.1.1
azure-batch==9.0.0
azure-cli==2.14.2
azure-cli-core==2.14.2
azure-cli-telemetry==1.0.6
azure-common==1.1.25
azure-core==1.8.2
azure-cosmos==3.2.0
azure-datalake-store==0.0.51
azure-functions-devops-build==0.0.22
azure-graphrbac==0.61.1
azure-identity==1.4.1
azure-keyvault==1.1.0
azure-keyvault-administration==4.0.0b2
azure-loganalytics==0.1.0
azure-mgmt-advisor==2.0.1
azure-mgmt-apimanagement==0.2.0
azure-mgmt-appconfiguration==0.6.0
azure-mgmt-applicationinsights==0.1.1
azure-mgmt-authorization==0.61.0
azure-mgmt-batch==9.0.0
azure-mgmt-batchai==2.0.0
azure-mgmt-billing==0.2.0
azure-mgmt-botservice==0.2.0
azure-mgmt-cdn==5.0.0
azure-mgmt-cognitiveservices==6.3.0
azure-mgmt-compute==14.0.0
azure-mgmt-consumption==2.0.0
azure-mgmt-containerinstance==1.5.0
azure-mgmt-containerregistry==2.8.0
azure-mgmt-containerservice==9.4.0
azure-mgmt-core==1.2.0
azure-mgmt-cosmosdb==1.0.0
azure-mgmt-datalake-analytics==0.2.1
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-datamigration==0.1.0
azure-mgmt-deploymentmanager==0.2.0
azure-mgmt-devtestlabs==4.0.0
azure-mgmt-dns==2.1.0
azure-mgmt-eventgrid==3.0.0rc7
azure-mgmt-eventhub==4.1.0
azure-mgmt-hdinsight==1.7.0
azure-mgmt-imagebuilder==0.4.0
azure-mgmt-iotcentral==3.0.0
azure-mgmt-iothub==0.12.0
azure-mgmt-iothubprovisioningservices==0.2.0
azure-mgmt-keyvault==2.2.0
azure-mgmt-kusto==0.3.0
azure-mgmt-loganalytics==0.7.0
azure-mgmt-managedservices==1.0.0
azure-mgmt-managementgroups==0.2.0
azure-mgmt-maps==0.1.0
azure-mgmt-marketplaceordering==0.2.1
azure-mgmt-media==2.2.0
azure-mgmt-monitor==0.11.0
azure-mgmt-msi==0.2.0
azure-mgmt-netapp==0.12.0
azure-mgmt-network==12.0.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==0.5.0
azure-mgmt-privatedns==0.1.0
azure-mgmt-rdbms==3.1.0rc1
azure-mgmt-recoveryservices==0.4.0
azure-mgmt-recoveryservicesbackup==0.6.0
azure-mgmt-redhatopenshift==0.1.0
azure-mgmt-redis==7.0.0rc2
azure-mgmt-relay==0.1.0
azure-mgmt-reservations==0.6.0
azure-mgmt-resource==10.3.0
azure-mgmt-search==2.1.0
azure-mgmt-security==0.4.1
azure-mgmt-servicebus==0.6.0
azure-mgmt-servicefabric==0.5.0
azure-mgmt-signalr==0.4.0
azure-mgmt-sql==0.21.0
azure-mgmt-sqlvirtualmachine==0.5.0
azure-mgmt-storage==11.2.0
azure-mgmt-synapse==0.3.0
azure-mgmt-trafficmanager==0.51.0
azure-mgmt-web==0.48.0
azure-multiapi-storage==0.5.2
azure-nspkg==3.0.2
azure-storage-blob==12.5.0
azure-storage-common==1.4.2
azure-storage-queue==12.1.3
azure-synapse-accesscontrol==0.2.0
azure-synapse-artifacts==0.3.0
azure-synapse-spark==0.2.0
**azureml-accel-models==1.18.0
azureml-automl-core==1.18.0
azureml-automl-runtime==1.18.0
azureml-cli-common==1.18.0
azureml-contrib-dataset==1.18.0
azureml-contrib-fairness==1.18.0
azureml-contrib-gbdt==1.18.0
azureml-contrib-interpret==1.18.0
azureml-contrib-notebook==1.18.0
azureml-contrib-pipeline-steps==1.18.0
azureml-contrib-reinforcementlearning==1.18.0
azureml-contrib-server==1.18.0
azureml-contrib-services==1.18.0
azureml-core==1.18.0
azureml-datadrift==1.18.0
azureml-dataprep==2.4.2
azureml-dataprep-native==24.0.0
azureml-dataprep-rslex==1.2.2
azureml-dataset-runtime==1.18.0
azureml-defaults==1.18.0
azureml-explain-model==1.18.0
azureml-interpret==1.18.0
azureml-mlflow==1.18.0
azureml-model-management-sdk==1.0.1b6.post1
azureml-opendatasets==1.18.0
azureml-pipeline==1.18.0
azureml-pipeline-core==1.18.0
azureml-pipeline-steps==1.18.0
azureml-samples @ file:///mnt/jupyter-azsamples
azureml-sdk==1.18.0
azureml-telemetry==1.18.0
azureml-tensorboard==1.18.0
azureml-train==1.18.0
azureml-train-automl==1.18.0
azureml-train-automl-client==1.18.0
azureml-train-automl-runtime==1.18.0
azureml-train-core==1.18.0
azureml-train-restclients-hyperdrive==1.18.0
azureml-widgets==1.18.0**
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache==1.6.1
backports.tempfile==1.0
backports.weakref==1.0.post1
bcrypt==3.2.0
beautifulsoup4==4.9.3
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1600454382015/work
blessings==1.7
blis==0.2.4
boto==2.49.0
boto3==1.15.18
botocore==1.18.18
Bottleneck==1.3.2
brotlipy==0.7.0
cached-property==1.5.2
cachetools==4.1.1
certifi==2020.6.20
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1602537220450/work
chardet @ file:///home/conda/feedstock_root/build_artifacts/chardet_1602255305250/work
click==7.1.2
cloudpickle==1.6.0
colorama==0.4.4
colorful==0.5.4
configparser==3.7.4
contextlib2==0.6.0.post1
contextvars==2.4
convertdate @ file:///home/conda/feedstock_root/build_artifacts/convertdate_1605102623033/work
coremltools @ git+https://github.com/apple/coremltools@13c064ed99ab1da7abea0196e4ddf663ede48aad
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography_1604179078642/work
cssselect==1.1.0
cycler==0.10.0
cymem==2.0.4
Cython @ file:///tmp/build/80754af9/cython_1594831565616/work
databricks-cli==0.14.0
dataclasses==0.7
decorator==4.4.2
defusedxml==0.6.0
dill==0.3.3
distro==1.5.0
dm-tree==0.1.5
docker==4.3.1
dotnetcore2==2.1.17
en-core-web-sm @ https://aka.ms/automl-resources/packages/en_core_web_sm-2.1.0.tar.gz
encrypted-inference==0.9
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1602701731856/work/dist/entrypoints-0.3-py2.py3-none-any.whl
enum34==1.1.10
fabric==2.5.0
fairlearn==0.4.6
fastai==1.0.61
fastprogress==1.0.0
fbprophet==0.5
filelock==3.0.12
fire==0.3.1
flake8==3.8.4
Flask==1.0.3
Flask-Cors==3.0.9
fusepy==3.0.1
future==0.18.2
gast==0.2.2
gensim==3.8.3
gevent==20.9.0
gitdb==4.0.5
GitPython==3.1.11
google==3.0.0
google-api-core==1.23.0
google-auth==1.23.0
google-auth-oauthlib==0.4.2
google-pasta==0.2.0
googleapis-common-protos==1.52.0
gorilla==0.3.0
gpustat==0.6.0
greenlet==0.4.17
grpcio==1.33.2
gunicorn==19.9.0
gym==0.17.3
h5py==3.1.0
hiredis==1.1.0
holidays==0.9.11
horovod==0.19.1
humanfriendly==8.2
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1593328102638/work
idna-ssl==1.1.0
imageio==2.9.0
immutables==0.14
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1602263269022/work
interpret-community==0.15.3
interpret-core==0.2.1
invoke==1.4.1
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1602682803509/work/dist/ipykernel-5.3.4-py3-none-any.whl
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1593235451385/work
ipython-genutils==0.2.0
ipywidgets==7.5.1
isodate==0.6.0
isort==5.6.4
itsdangerous==1.1.0
javaproperties==0.5.1
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1605054537831/work
jeepney==0.4.3
Jinja2==2.11.2
jmespath==0.10.0
joblib==0.14.1
jsmin==2.2.2
json-logging-py==0.2
json5 @ file:///home/conda/feedstock_root/build_artifacts/json5_1600692310011/work
jsondiff==1.2.0
jsonpickle==1.4.1
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema_1602551949684/work
jupyter==1.0.0
jupyter-client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1598486169312/work
jupyter-console==6.2.0
jupyter-core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1602537281137/work
jupyterlab==2.1.4
jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1601375948261/work
jupyterlab-server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1593951277307/work
jupytext==1.6.0
Keras==2.3.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
keras2onnx==1.6.0
kiwisolver==1.3.1
knack==0.7.2
lazy-object-proxy==1.4.3
liac-arff==2.5.0
lightgbm==2.3.0
lunardate==0.2.0
lxml==4.6.1
lz4==3.1.0
Mako==1.1.3
Markdown==3.3.3
markdown-it-py==0.5.6
MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1602267314491/work
matplotlib==3.2.1
mccabe==0.6.1
mistune @ file:///home/conda/feedstock_root/build_artifacts/mistune_1602381743210/work
mkl-fft==1.2.0
mkl-random==1.1.0
mkl-service==2.3.0
mlflow==1.11.0
mock==4.0.2
msal==1.6.0
msal-extensions==0.2.2
msgpack==1.0.0
msrest==0.6.19
msrestazure==0.6.4
multidict==5.0.0
murmurhash==1.0.4
nb-conda @ file:///home/conda/feedstock_root/build_artifacts/nb_conda_1603265698826/work
nb-conda-kernels @ file:///home/conda/feedstock_root/build_artifacts/nb_conda_kernels_1603235541399/work
nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1602859080374/work
nbconvert @ file:///home/conda/feedstock_root/build_artifacts/nbconvert_1603792523988/work
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1602732862338/work
ndg-httpsclient==0.5.1
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1604290829246/work
networkx==2.5
nimbusml==1.8.0
notebook @ file:///home/conda/feedstock_root/build_artifacts/notebook_1605103640761/work
numexpr==2.7.1
numpy==1.18.5
nvidia-ml-py3==7.352.0
oauthlib==3.1.0
olefile==0.46
onnx==1.7.0
onnxconverter-common==1.6.0
onnxmltools==1.4.1
onnxruntime==1.3.0
opencensus==0.7.11
opencensus-context==0.1.2
opencv-python==4.4.0.46
opencv-python-headless==4.3.0.36
opt-einsum==3.3.0
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1589925210001/work
pandas==0.25.3
pandas-ml==0.6.1
pandocfilters==1.4.3
papermill==1.2.1
paramiko==2.7.2
parsel==1.6.0
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1595548966091/work
pathspec==0.8.0
patsy==0.5.1
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1602535608087/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow==6.2.1
pkginfo==1.6.1
plac==0.9.6
pluggy==0.13.1
pmdarima==1.1.1
portalocker==1.7.1
preshed==2.0.1
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1590412252446/work
prometheus-flask-exporter==0.18.1
prompt-toolkit==3.0.5
protobuf==3.13.0
psutil==5.7.3
psycopg2==2.8.4
ptyprocess==0.6.0
py-cpuinfo==5.0.0
py-spy==0.3.3
py4j==0.10.9
pyarrow==1.0.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycocotools==2.0.0
pycodestyle==2.6.0
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pydocstyle==5.1.1
pyflakes==2.2.0
pyglet==1.5.0
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1603558917696/work
PyJWT==1.7.1
pylint==2.6.0
PyMeeus @ file:///home/conda/feedstock_root/build_artifacts/pymeeus_1589222711601/work
PyNaCl==1.4.0
pyodbc===4.0.0-unsupported
pyOpenSSL==19.1.0
pyparsing==2.4.7
pyrsistent @ file:///home/conda/feedstock_root/build_artifacts/pyrsistent_1602259978628/work
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1602326920180/work
pyspark==3.0.1
pystan==2.19.0.0
python-dateutil==2.8.1
python-editor==1.0.4
python-jsonrpc-server==0.4.0
python-language-server==0.35.0
pytorch-transformers==1.0.0
pytz==2020.4
PyWavelets==1.1.1
PyYAML==5.3.1
pyzmq==19.0.2
qtconsole==4.7.7
QtPy==1.9.0
querystring-parser==1.2.4
ray==1.0.1
redis==3.4.1
regex==2020.10.28
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1592425495151/work
requests-oauthlib==1.3.0
rope==0.18.0
rsa==4.6
ruamel.yaml==0.16.12
ruamel.yaml.clib==0.2.2
s3transfer==0.3.3
scikit-image==0.17.2
scikit-learn==0.22.2.post1
scipy @ file:///tmp/build/80754af9/scipy_1597686625380/work
scp==0.13.3
scrapbook==0.2.0
SecretStorage==3.1.2
Send2Trash==1.5.0
sentencepiece==0.1.94
setuptools-git==1.2
shap==0.34.0
sip==4.19.24
six==1.15.0
skl2onnx==1.4.9
sklearn==0.0
sklearn-pandas==1.7.0
smart-open==1.9.0
smmap==3.0.4
snowballstemmer==2.0.0
soupsieve==2.0.1
spacy==2.1.8
SQLAlchemy==1.3.13
sqlparse==0.4.1
srsly==1.0.4
sshtunnel==0.1.5
statsmodels==0.10.2
tabulate==0.8.7
tenacity==6.2.0
tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
tensorboardX==2.1
tensorflow==2.1.0
tensorflow-estimator==2.1.0
tensorflow-gpu==2.1.0
termcolor==1.1.0
terminado @ file:///home/conda/feedstock_root/build_artifacts/terminado_1602679586915/work
testpath==0.4.4
textwrap3==0.9.2
thinc==7.0.8
threadpoolctl @ file:///tmp/tmp9twdgx9k/threadpoolctl-2.1.0-py3-none-any.whl
tifffile==2020.9.3
toml==0.10.2
torch==1.4.0
torchvision==0.5.0
tornado==6.1
tqdm==4.51.0
traitlets==4.3.3
typed-ast==1.4.1
typing-extensions==3.7.4.3
ujson==4.0.1
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1603125704209/work
vsts==0.1.25
vsts-cd-manager==1.0.2
w3lib==1.22.0
waitress==1.4.4
wasabi==0.8.0
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1600965781394/work
webencodings==0.5.1
websocket-client==0.57.0
websockets==8.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wrapt==1.12.1
xgboost==0.90
xmltodict==0.12.0
yapf==0.30.0
yarl==1.6.2
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1603668650351/work
zope.event==4.5.0
zope.interface==5.2.0

==========

**Comment by sagarsumant** [comment]
I assume you are running notebooks as it is, in that case it is expected because of this flag. This flag ensures that user gets to see only best model trained for that AutoML run/ data partition. In case you want to see all the models simply set this flag to True and you would see all the models that were trained. Note that only best model based on the primary metric gets registered.

![image](https://user-images.githubusercontent.com/109864/99834168-02bbbe80-2b18-11eb-8512-c415018ccf3d.png)

Also note that, we recommend **"track_child_runs": False** when you want to train thousands of models (AutoML runs) for scale/performance benefits.

**Comment by jingwora** [comment]
@sagarsumant
Thank you for your great support.
You are right.  After I change track_child_runs to Run, all models are registed. 

In summary:
To run example of manymodels notebooks, I would recommend to create new azure compute instant and clone new manymodels github. 
There might be some compatibility issue from package upgrade.
