### ISSUE TITLE
Notebook VM?

### ISSUE THREAD

**Issue by pawarbi** [microsoft/solution-accelerator-many-models#112]
The post recommends using Notebook VM to get up and running quickly but Notebook VMs have been discontinued. Did you mean Compute Instance VM? 

https://github.com/microsoft/solution-accelerator-many-models#2-configure-development-environment

**Comment by sagarsumant** [comment]
Yes you are right. We need to update our documentation, @Aniththa for that. Notebook VM is now replaced with Compute Instance, you can get started with that [here](https://docs.microsoft.com/en-us/azure/machine-learning/concept-compute-instance).
