### ISSUE TITLE
Forecasting training data

### ISSUE THREAD

**Issue by jingwora** [microsoft/solution-accelerator-many-models#113]
In Forecasting Pipeline Notebook, 
we can predict testing data.
Is there option to forecast from training dataset?

**Comment by sagarsumant** [comment]
Can you clarify more, do you mean do a train/test split of the training data and then do a prediction on the data?

**Comment by jingwora** [comment]
Thank you for your great support.
Refer to 03_AutoML_Forecasting_Pipeline.ipynb.
We want to input X_train and get y_predict.
However, there is an error when I use X_train as below.

From my understanding, if we change from model.forecast() to model.predict(),
we can do forecasting with X_train.
I have changed code in 03_AutoML_Forecasting_Pipeline/scripts/forecast.py (line 101) as below. 
But there is still an error.
From: y_predictions, X_trans = model.forecast(
To: y_predictions, X_trans = model.**predict**(

Could you let me know how to get y_predict from X_train?

Reference:

-----

Detail error
{
    "error": {
        "code": "UserError",
        "message": "AzureMLCompute job failed.\nJobFailed: Submitted script failed with a non-zero exit code; see the driver log file for details.",
        "details": []
    },
    "correlation": {
        "operation": null,
        "request": "fa72e67017c06848"
    },
    "environment": "japaneast",
    "location": "japaneast",
    "time": "2020-11-24T08:45:37.707277Z",
    "componentName": "execution-worker"
}
	InnerException None
	ErrorResponse 
{


-----

**Comment by sagarsumant** [comment]
Unfortunately we do not support the forecasting using trained data. I would recommend split your data into train/test before start of the training and after training use test data for doing forecasts. Let me know if this answers your question, else I can loop people specializing in the forecasting part involved to go in more details on your scenario.

**Comment by jingwora** [comment]
@sagarsumant 
Thanks for your great support.
I got it. The model is not support for forecasting using trained data.
By the way, if you plan to expand the project, forecasting using trained data should be a good candidate.
