### ISSUE TITLE
Incorrect argument name in many_models_inference_driver.py

### ISSUE THREAD

**Issue by felixcollins** [microsoft/solution-accelerator-many-models#126]
In the file many_models_inference_driver.py. On line 9 
`parser.add_argument("--partition_column_names", '--nargs', nargs='*', type=str, help="partition_column_names")`

This should be 
`parser.add_argument("--partition_column_names", nargs='*', type=str, help="partition_column_names")`

While this is not a particularly dangerous bug it seems to be incorrect as it is adding an alternative argument name of "nargs" for the partition_column_names argument. Maybe it is the result of a copy paste error...

**Comment by cartacioS** [comment]
Hi @felixcollins - it looks like the file and line of code mentioned above no longer exist or this issue was resolved. I will close this issue, but please reopen or open a new issue should you still observe the same practice.
