### ISSUE TITLE
DataFrame column names are stripped when combining timeseries forecast output.

### ISSUE THREAD

**Issue by felixcollins** [microsoft/solution-accelerator-many-models#128]
I'm running a timeseries forecast using the many models accelerator and the results come back in a plain text file with whitespace delimited values. There are no headers in the first row. The return value from each mini batch is a pandas DataFrame with columns names. These are being combined to make the output file but the column names are lost.

**Comment by cartacioS** [comment]
To add header in output automatically, please add below argument when creating the step.

Step = ParallelRunStep(
              …
arguments=["--append_row_dataframe_header", True]
…
)

**Comment by deeptim123** [comment]
If you are using AutoMLPipelineBuilder.get_many_models_batch_inference_steps to build the parallel run step you can pass that as arguments as follows

inference_steps = AutoMLPipelineBuilder.get_many_models_batch_inference_steps(
                                                                           ...
                                                                           arguments=["--append_row_dataframe_header", True]
                                                                           ...)

![image](https://user-images.githubusercontent.com/41402549/118324324-bb0a6400-b4b6-11eb-831d-9a0bed5c8e69.png)

**Comment by felixcollins** [comment]
Thanks I'll give it a shot and close the ticket when it is going.

**Comment by felixcollins** [comment]
That worked. Thanks!
