### ISSUE TITLE
Model name can not be made unique to a given automl config / pipeline.

### ISSUE THREAD

**Issue by felixcollins** [microsoft/solution-accelerator-many-models#133]
Say for example, that the many models training accelerator (MMA) is to be used with two different automl configs in two pipelines but the same training data and partitions. The registered models will have the same names in the registry.  There is, as far as I can see currently no way to append information to the model name to make it unique in this situation. 

I suggested solution would be to allow the user to optionally pass in a model name prefix or suffix. It then becomes the API consumers responsibility to make the name unique in what ever scope they choose.

**Comment by cartacioS** [comment]
We can combine and track this feedback and request within this issue: https://github.com/microsoft/solution-accelerator-many-models/issues/132

Closing, but please reopen if you feel it is not adequately addressed.
