### ISSUE TITLE
Issue in 02_CustomScript_Training_Pipeline

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/solution-accelerator-many-models#145]
Hi , while running cell 14 in **6.2 Convert the file to a dataframe** we are getting error as below:
![image](https://user-images.githubusercontent.com/57964598/146769213-b80b01f4-739e-49a3-abe1-b909a802ed1f.png)
![image](https://user-images.githubusercontent.com/57964598/146769264-33bc6139-d4fa-4b3b-95e9-5e674332c2ec.png)
Could you please take a look into this

**Comment by himanshuahlawat31** [comment]
Hi, could you please take a look into this as we are stuck on this step

**Comment by nchandhi** [comment]
Hi @himanshuahlawat31,

Change the code in line 3 of the cell to below to fix the error:
df.columns = ['Store', 'Brand', 'Model', 'File Name', 'ModelName', 'StartTime', 'EndTime', 'Duration',
              'MSE', 'RMSE', 'MAE', 'MAPE', 'Index', 'Number of Models', 'Status','RunID']

**Comment by himanshuahlawat31** [comment]
HI @nchandhi 

Thanks for the response

Could you please update the notebook code with same, we have tested the code and it worked

**Comment by cartacioS** [comment]
Merged suggested change:https://github.com/microsoft/solution-accelerator-many-models/pull/146

Thanks!
