### ISSUE TITLE
Need wait_for_completion

### ISSUE THREAD

**Issue by gvashishtha** [microsoft/solution-accelerator-many-models#71]
If you try to run all cells in  02_Training_Pipeline, you get:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-23-88332502ed04> in <module>
      9     return  os.path.join(target_dir, 'azureml', step_hash, 'training_output')
     10 
---> 11 file_path = download_results(run, 'output')
     12 file_path

<ipython-input-23-88332502ed04> in download_results(run, target_dir)
      2 
      3 def download_results(run, target_dir=None):
----> 4     stitch_run = run.find_step_run("many-models-training")[0]
      5     port_data = stitch_run.get_output_data("training_output")
      6     print(port_data)

IndexError: list index out of range

on the next cell. I believe this is due to the lack of a `wait_for_completion()` step in the previous cell.

**Comment by krishnaanumalasetty** [comment]
That's right. Need to wait until the run is complete.
