### ISSUE TITLE
Step 6.1 KeyError 02_Training_Pipeline

### ISSUE THREAD

**Issue by gvashishtha** [microsoft/solution-accelerator-many-models#72]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-21-88332502ed04> in <module>
      9     return  os.path.join(target_dir, 'azureml', step_hash, 'training_output')
     10 
---> 11 file_path = download_results(run, 'output')
     12 file_path

<ipython-input-21-88332502ed04> in download_results(run, target_dir)
      3 def download_results(run, target_dir=None):
      4     stitch_run = run.find_step_run("many-models-training")[0]
----> 5     port_data = stitch_run.get_output_data("training_output")
      6     print(port_data)
      7     port_data.download(target_dir, show_progress=True)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/pipeline/core/run.py in get_output_data(self, name)
    690         :rtype: azureml.pipeline.core.PortDataReference
    691         """
--> 692         return self.get_output(name).get_port_data_reference()
    693 
    694     def wait_for_completion(self, show_output=True, timeout_seconds=sys.maxsize, raise_on_error=True):

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/pipeline/core/run.py in get_output(self, name)
    678         :rtype: azureml.pipeline.core.StepRunOutput
    679         """
--> 680         return self._step_run_provider.get_output(self, self._context, self._pipeline_run_id, self._node_id, name)
    681 
    682     def get_output_data(self, name):

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/pipeline/core/_aeva_provider.py in get_output(self, step_run, context, pipeline_run_id, node_id, name)
   1230         """
   1231         node_outputs = self._service_caller.get_node_outputs_async(pipeline_run_id, node_id)
-> 1232         return StepRunOutput(context, pipeline_run_id, step_run, name, node_outputs[name])
   1233 
   1234 

KeyError: 'training_output'

**Comment by krishnaanumalasetty** [comment]
Need to wait until the experiment run that was submitted to Azure Compute Cluster is complete before running this cell.
